name: Package Application with Pyinstaller

on:
  push:
    tags:
      - '*'
      # branches: [ main ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: bills-table-${{  github.ref_name }}
        path: src/dist/windows

    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: src/dist/windows/bills-table-${{  github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
